name: 'Setup action'
description: 'Set up source code'
runs:
  using: 'composite'
  steps:
    - name: Install Nodejs
      uses: actions/setup-node@v4
      with:
          node-version: '20'
    - name: Install pnpm
      run: |
          npm install -g pnpm &&
          pnpm install --frozen-lockfile
      shell: bash